name: Setup mermaid-cli
description: Setup/Install mermaid-cli for GitHub Actions
branding:
  icon: git-merge
  color: red
inputs:
  version:
    description: mermaid-cli version
    default: latest
  token:
    description: GitHub token to avoid API rate limiting
    default: ${{ github.token }}
    
runs:
  using: composite
  steps:
    - name: Get mermaid-cli version
      id: version
      shell: bash
      run: $GITHUB_ACTION_PATH/scripts/version.sh
      env:
        version: ${{ inputs.version }}
        GITHUB_TOKEN: ${{ inputs.token }}
        
    - name: Restore mermaid-cli cache
      id: cache
      uses: actions/cache/restore@v4
      with:
        path: ${{ runner.tool_cache }}/mermaid-cli
        key: mermaid-cli-${{ steps.version.outputs.version }}-${{ runner.os }}
        
    - name: Download mermaid-cli
      if: '! steps.cache.outputs.cache-hit'
      shell: bash
      working-directory: ${{ runner.temp }}
      run: $GITHUB_ACTION_PATH/scripts/download.sh
      env:
        version: ${{ steps.version.outputs.version }}
        
    - name: Install mermaid-cli on tool cache
      uses: AnimMouse/tool-cache@v1
      with:
        folder_name: mermaid-cli
        cache_hit: ${{ steps.cache.outputs.cache-hit }}
        
    - name: Save mermaid-cli cache
      if: '! steps.cache.outputs.cache-hit'
      uses: actions/cache/save@v4
      with:
        path: ${{ runner.tool_cache }}/mermaid-cli
        key: mermaid-cli-${{ steps.version.outputs.version }}-${{ runner.os }}
        
    - name: Symlink mmdc on tool cache
      shell: bash
      run: ln -s ${{ runner.tool_cache }}/mermaid-cli/node_modules/.bin/mmdc ${{ runner.tool_cache }}/mermaid-cli/mmdc